name: Pull Request
title: Pull Request for xxx
description: Pull Request
body:
  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I've read the [contribution guidelines](https://github.com/EdurtIO/incubator-datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree
          required: true
  - type: checkboxes
    attributes:
      label: Affected Module
      description: Which modules have been changed.
      options:
        - label: Server
        - label: Web
        - label: Plugin
        - label: Docs
        - label: Other
  - type: textarea
    attributes:
      label: To change the details
      description: List of change details of the current pull request
    validations:
      required: true
