site_name: DataCap (incubator)
site_url: https://databap.incubator.edurt.io/
site_author: EdurtIO
site_description: >-
  DataCap is integrated software for data transformation, integration and visualization.
repo_name: EdurtIO/incubator-datacap
repo_url: https://github.com/EdurtIO/incubator-datacap
edit_uri: "https://github.com/EdurtIO/incubator-datacap/blob/master/docs/docs"

copyright: Copyright &copy; 2022 EdurtIO

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/open-source-initiative
  favicon: material/open-source-initiative
  include_search_page: false
  search_index_only: true
  language: zh
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EdurtIO
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/qianmoQ/
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EdurtIO
      repo: incubator-datacap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

use_directory_urls: false
plugins:
  - i18n:
      default_language: zh
      languages:
        en: English
        zh: 简体中文
      nav_translations:
        zh:
          home: 主页
          developer_guide: 开发指南
          developer_guide_env: 开发环境
          developer_guide_plugin: 自定义插件
          blog: 博客
          2022: 2022
          springboot-hive-jdbc-v2: sss
          documentation: 文档
          documentation_install: 安装
          documentation_query: 查询
          documentation_history: 历史
          documentation_database: 连接数据库
          documentation_database_mysql: MySQL
          documentation_database_clickhouse: ClickHouse
          documentation_database_kylin: Kylin
          documentation_database_oracle: Oracle
          documentation_v120: 1.2.0-SNAPSHOT
          documentation_v120_plugin_cratedb: CrateDB
          release: 发布日志
          release_20221015: 1.0.0.20221015
          release_20221115: 1.1.0.20221115 (latest)
        en:
          home: Home
          developer_guide: Developer guide
          developer_guide_env: Development environment
          developer_guide_plugin: Custom Plugin
          blog: Blog
          springboot-hive-jdbc-v2: sss
          documentation: Documentation
          documentation_install: Installation
          documentation_query: Query
          documentation_history: History
          documentation_database: Connecting to Databases
          documentation_database_mysql: MySQL
          documentation_database_clickhouse: ClickHouse
          documentation_database_kylin: Kylin
          documentation_database_oracle: Oracle
          documentation_v120: 1.2.0-SNAPSHOT
          documentation_v120_plugin_cratedb: CrateDB
          release: Release Note
          release_20221015: 1.0.0.20221015
          release_20221115: 1.1.0.20221115 (latest)
  - search
  - blog:
      archive: false
      categories: false
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - git-authors
  - redirects:
      redirect_maps:
        release-latest.md: release/1.1.0.20221115.md

nav:
  - home: index.md
  - documentation:
      - documentation_install: reference/get_started/install.md
      - documentation_query: reference/get_started/query.md
      - documentation_history: reference/get_started/history.md
      - documentation_database:
        - documentation_v120:
          - documentation_v120_plugin_cratedb: reference/plugin/v120/cratedb.md
        - documentation_database_mysql: reference/database/mysql.md
        - documentation_database_clickhouse: reference/database/clickhouse.md
        - documentation_database_kylin: reference/database/kylin.md
        - documentation_database_oracle: reference/database/oracle.md
  - developer_guide:
      - developer_guide_env: developer_guide/env.md
      - developer_guide_plugin: developer_guide/plugin.md
  - release:
      - release_20221115: release/1.1.0.20221115.md
      - release_20221015: release/1.0.0.20221015.md
  - blog:
    - blog/index.md
