name: Publish Self Host

on: [push]

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chmod
        run: chmod 755 ./mvnw
      - name: Package
        run: |
          wget -O /tmp/jdk-8u60-linux-x64.tar.gz http://software.cdn.ttxit.com/oracle/jdk-8u60-linux-x64.tar.gz
          mkdir -p /opt/java/
          tar -xzf /tmp/jdk-8u60-linux-x64.tar.gz -C /opt/java/
          export JAVA_HOME=/opt/java/jdk1.8.0_60
          export PATH=$JAVA_HOME/bin:$PATH
          export CLASSPATH=.:$JAVA_HOME/bin/dt.jar:$JAVA_HOME/lib/tools.jar
          java -version
          ./mvnw clean install package -Dfindbugs.skip -Dgpg.skip -Dcheckstyle.skip -DskipTests=true
      - name: Upload
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
          ARGS: -avz --delete --exclude='*.pyc'
          SERVER_PORT: '22'
          FOLDER: dist/datacap-release.tar.gz
          SERVER_IP: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER_NAME }}
          SERVER_DESTINATION: /root/app/
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /root/app && cd datacap && sh ./bin/shutdown.sh
            cd /root/app && rm -rf datacap
            cd /root/app && tar -xvzf datacap-release.tar.gz
            cd /root/app && chmod -R 777 datacap
            cd /root/app && cd datacap && sh ./bin/shutdown.sh && sh ./bin/startup.sh
            cd /root/app && rm -rf datacap-release.tar.gz
